"use client";

import { useState } from "react";

export const TERMS_VERSION = "2026-07-27";

export default function LegalCenter() {
  const [open, setOpen] = useState<"privacy" | "terms" | "data" | null>(null);
  return (
    <section className="legal-center" aria-labelledby="legal-title">
      <div className="legal-heading"><div><p className="section-kicker">Minh bạch và an toàn</p><h2 id="legal-title">Dữ liệu thuộc quyền kiểm soát của người dùng.</h2></div><p>SỸ LAND công bố rõ dữ liệu nào được xử lý trên máy, dữ liệu nào được gửi lên máy chủ và trách nhiệm kiểm tra kết quả nghiệp vụ.</p></div>
      <div className="legal-grid">
        <article><span>01</span><h3>Chính sách bảo mật</h3><p>Tài khoản và trạng thái bản quyền được lưu trên máy chủ. Hồ sơ văn phòng mặc định xử lý cục bộ; video Creator được gửi tới máy chủ xử lý riêng khi người dùng chủ động yêu cầu.</p><button type="button" onClick={() => setOpen(open === "privacy" ? null : "privacy")}>Xem chính sách</button></article>
        <article><span>02</span><h3>Điều khoản sử dụng</h3><p>SỸ LAND là công cụ hỗ trợ. Người dùng và chuyên viên chịu trách nhiệm kiểm tra nguồn, cảnh báo và kết quả trước khi sử dụng trong hồ sơ chính thức.</p><button type="button" onClick={() => setOpen(open === "terms" ? null : "terms")}>Xem điều khoản</button></article>
        <article><span>03</span><h3>Xử lý và lưu giữ dữ liệu</h3><p>Không tự động tải hồ sơ địa chính lên máy chủ. Video Creator chỉ được tiếp nhận sau khi người dùng xác nhận quyền và tệp kết quả mặc định hết hạn sau 24 giờ.</p><button type="button" onClick={() => setOpen(open === "data" ? null : "data")}>Xem nguyên tắc</button></article>
      </div>
      {open && <div className="legal-detail" role="region" aria-live="polite"><button type="button" onClick={() => setOpen(null)} aria-label="Đóng">×</button>{open === "privacy" ? <><h3>Chính sách bảo mật SỸ LAND</h3><ul><li>Thu thập tối thiểu thông tin tài khoản, email, tên hiển thị, bản quyền, thiết bị đã băm và yêu cầu hỗ trợ.</li><li>Video Creator được xử lý trên máy chủ riêng; bản ghi tác vụ, nguồn, xác nhận quyền và số phút sử dụng được lưu theo tài khoản.</li><li>Whisper nhận diện trên worker SỸ LAND; phần lời thoại được gửi tới nhà cung cấp AI đã chọn để dịch và phần tiếng Việt được gửi tới dịch vụ tạo giọng đọc.</li><li>Không bán dữ liệu cá nhân hoặc dùng video, lời thoại hay hồ sơ nghiệp vụ để quảng cáo.</li><li>Người dùng có thể yêu cầu xuất hoặc xóa dữ liệu tài khoản theo quy trình xác minh.</li><li>Không đưa service role key hoặc khóa AI vào website và phần mềm người dùng.</li></ul></> : open === "terms" ? <><h3>Điều khoản sử dụng</h3><ul><li>Không sử dụng công cụ để sửa đổi, giả mạo hoặc che giấu thông tin hồ sơ.</li><li>Chỉ xử lý video do người dùng sở hữu hoặc đã được chủ sở hữu cho phép dịch, lồng tiếng và xuất bản.</li><li>Quét nguồn Creator chỉ đánh giá metadata và rủi ro; không phải giấy chứng nhận bản quyền hoặc kết luận pháp lý.</li><li>Không vượt đăng nhập, cookie, nội dung riêng tư, hội viên hoặc giới hạn truy cập của nền tảng.</li><li>Người dùng chịu trách nhiệm tuân thủ điều khoản nền tảng, quyền tác giả, quyền hình ảnh và pháp luật khi đăng TikTok, Reels hoặc Shorts.</li><li>Bản quyền SỸ LAND được cấp theo email, thời hạn, gói và hạn mức; tài khoản vi phạm có thể bị khóa.</li></ul></> : <><h3>Nguyên tắc xử lý và lưu giữ dữ liệu</h3><ul><li>Word, PDF, Excel và OCR trên web mặc định thực hiện ngay trên thiết bị.</li><li>Video tải lên hoặc video công khai từ liên kết chỉ được đưa vào máy chủ Creator sau khi người dùng xác nhận quyền sử dụng.</li><li>Tệp nguồn và tệp trung gian được xóa sau khi xử lý; MP4 kết quả mặc định được giữ tối đa 24 giờ rồi tự động xóa.</li><li>Metadata nguồn, bằng chứng xác nhận quyền, trạng thái tác vụ và sổ hạn mức có thể được giữ để vận hành, hỗ trợ và kiểm toán.</li><li>Không tải GCN, CCCD, hồ sơ địa chính hoặc dữ liệu nhạy cảm vào Creator hay biểu mẫu hỗ trợ.</li><li>Nhật ký và dữ liệu Creator được tách theo tài khoản bằng Row Level Security.</li></ul></>}<small>Phiên bản điều khoản: {TERMS_VERSION}</small></div>}
    </section>
  );
}
